apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:mysql://<aws rds endpoint>:3306/restaurantdb?useSSL=false&allowPublicKeyRetrieval=true
  foodcataloguedb_url: jdbc:mysql://<aws rds endpoint>:3306/foodcataloguedb?useSSL=false&allowPublicKeyRetrieval=true
  userdb_url: jdbc:mysql://<aws rds endpoint>:3306/userdb?useSSL=false&allowPublicKeyRetrieval=true
  orderdb_url: mongodb+srv://<username>:<password>@<mongodb cluster endpoint>/?retryWrites=true&w=majority
  eureka_service_address: http://eureka-0.eureka-service:8761/eureka
 