spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/userdb
    url: jdbc:mysql://host.docker.internal:3306/userdb
    username: root
    password: ${DB_PWD}

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eurekafd:8761/eureka/
    fetch-registry: true
    register-with-eureka: true