spring:
  application:
    name: restaurant-service
  profiles:
    active: dev
  datasource:
    hikari:
      pool-name: RestaurantListingHikariCP
      minimum-idle: 3
      maximum-pool-size: 10
      connection-timeout: 10000
      idle-timeout: 600000
      max-lifetime: 1700000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
    
    
server:
  port: 9091
